spring:
  datasource:
    url: jdbc:mysql://mysql:3306/eventapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8mb4
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver

#
#  spring.datasource.url=${SPRING_DATASOURCE_URL}
#  spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#  spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}