spring:
  datasource:
    url: jdbc:mysql://localhost:3306/events?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 15
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml
    drop-first: false